package com.talaash.mapper;

import com.talaash.entity.Clue;
import com.talaash.entity.ClueExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    long countByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer clueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    List<Clue> selectByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    Clue selectByPrimaryKey(Integer clueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") Clue record, @Param("example") ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExample(@Param("record") Clue record, @Param("example") ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKey(Clue record);

    @Update("UPDATE talaash_db SET status = #{status} WHERE id = #{id}")
    int updateClueStatus(@Param("status") Integer status, @Param("id") Integer id);

}