package com.talaash.mapper;

import com.talaash.entity.Comment;
import com.talaash.entity.CommentExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    long countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);
}