package com.talaash.mapper;

import com.talaash.entity.DisappearedPerson;
import com.talaash.entity.DisappearedPersonExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface DisappearedPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    long countByExample(DisappearedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByExample(DisappearedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer disId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insert(DisappearedPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insertSelective(DisappearedPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    List<DisappearedPerson> selectByExampleWithBLOBs(DisappearedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    List<DisappearedPerson> selectByExample(DisappearedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    DisappearedPerson selectByPrimaryKey(Integer disId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") DisappearedPerson record, @Param("example") DisappearedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") DisappearedPerson record, @Param("example") DisappearedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExample(@Param("record") DisappearedPerson record, @Param("example") DisappearedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(DisappearedPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(DisappearedPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKey(DisappearedPerson record);
}