package com.talaash.mapper;

import com.talaash.entity.Family;
import com.talaash.entity.FamilyExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface FamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    long countByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    int deleteByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    int deleteByPrimaryKey(Integer familyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    int insert(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    int insertSelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    List<Family> selectByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    Family selectByPrimaryKey(Integer familyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Family record, @Param("example") FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    int updateByExample(@Param("record") Family record, @Param("example") FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    int updateByPrimaryKeySelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    int updateByPrimaryKey(Family record);
}