package com.talaash.mapper;

import com.talaash.entity.FriendLinkage;
import com.talaash.entity.FriendLinkageExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface FriendLinkageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    long countByExample(FriendLinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByExample(FriendLinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insert(FriendLinkage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insertSelective(FriendLinkage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    List<FriendLinkage> selectByExample(FriendLinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    FriendLinkage selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") FriendLinkage record, @Param("example") FriendLinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExample(@Param("record") FriendLinkage record, @Param("example") FriendLinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(FriendLinkage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKey(FriendLinkage record);
}