package com.talaash.mapper;

import com.talaash.entity.NavigationBar;
import com.talaash.entity.NavigationBarExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface NavigationBarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    long countByExample(NavigationBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByExample(NavigationBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer nid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insert(NavigationBar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int insertSelective(NavigationBar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    List<NavigationBar> selectByExample(NavigationBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    NavigationBar selectByPrimaryKey(Integer nid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") NavigationBar record, @Param("example") NavigationBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByExample(@Param("record") NavigationBar record, @Param("example") NavigationBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(NavigationBar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_navigation_bar
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    int updateByPrimaryKey(NavigationBar record);
}