package com.talaash.mapper;

import com.talaash.entity.User;
import com.talaash.entity.UserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_user
     *
     * @mbg.generated Thu Mar 26 18:55:39 CST 2020
     */
    int updateByPrimaryKey(User record);
}