package com.talaash.entity;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_article.article_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_article.title
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_article.picture
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_article.create_time
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_article.status
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_article.deleted
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_article.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_article.content
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_article
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_article.article_id
     *
     * @return the value of mj_article.article_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_article.article_id
     *
     * @param articleId the value for mj_article.article_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_article.title
     *
     * @return the value of mj_article.title
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_article.title
     *
     * @param title the value for mj_article.title
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_article.picture
     *
     * @return the value of mj_article.picture
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_article.picture
     *
     * @param picture the value for mj_article.picture
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_article.create_time
     *
     * @return the value of mj_article.create_time
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_article.create_time
     *
     * @param createTime the value for mj_article.create_time
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_article.status
     *
     * @return the value of mj_article.status
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_article.status
     *
     * @param status the value for mj_article.status
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_article.deleted
     *
     * @return the value of mj_article.deleted
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_article.deleted
     *
     * @param deleted the value for mj_article.deleted
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_article.user_id
     *
     * @return the value of mj_article.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_article.user_id
     *
     * @param userId the value for mj_article.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_article.content
     *
     * @return the value of mj_article.content
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_article.content
     *
     * @param content the value for mj_article.content
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_article
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", title=").append(title);
        sb.append(", picture=").append(picture);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", deleted=").append(deleted);
        sb.append(", userId=").append(userId);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}