package com.talaash.entity;

import java.io.Serializable;

public class Clue implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.clue_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer clueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.dis_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer disId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.photo
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.province
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.city
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.county
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.phone
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.wechat
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_clue.status
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.clue_id
     *
     * @return the value of mj_clue.clue_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getClueId() {
        return clueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.clue_id
     *
     * @param clueId the value for mj_clue.clue_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setClueId(Integer clueId) {
        this.clueId = clueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.dis_id
     *
     * @return the value of mj_clue.dis_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getDisId() {
        return disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.dis_id
     *
     * @param disId the value for mj_clue.dis_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setDisId(Integer disId) {
        this.disId = disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.photo
     *
     * @return the value of mj_clue.photo
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.photo
     *
     * @param photo the value for mj_clue.photo
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.province
     *
     * @return the value of mj_clue.province
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.province
     *
     * @param province the value for mj_clue.province
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.city
     *
     * @return the value of mj_clue.city
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.city
     *
     * @param city the value for mj_clue.city
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.county
     *
     * @return the value of mj_clue.county
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.county
     *
     * @param county the value for mj_clue.county
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setCounty(Integer county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.address
     *
     * @return the value of mj_clue.address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.address
     *
     * @param address the value for mj_clue.address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.phone
     *
     * @return the value of mj_clue.phone
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.phone
     *
     * @param phone the value for mj_clue.phone
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.wechat
     *
     * @return the value of mj_clue.wechat
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.wechat
     *
     * @param wechat the value for mj_clue.wechat
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_clue.status
     *
     * @return the value of mj_clue.status
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_clue.status
     *
     * @param status the value for mj_clue.status
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_clue
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clueId=").append(clueId);
        sb.append(", disId=").append(disId);
        sb.append(", photo=").append(photo);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", county=").append(county);
        sb.append(", address=").append(address);
        sb.append(", phone=").append(phone);
        sb.append(", wechat=").append(wechat);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}