package com.talaash.entity;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_comment.comment_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_comment.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_comment.article_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_comment.content
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_comment.create_time
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_comment.comment_id
     *
     * @return the value of mj_comment.comment_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_comment.comment_id
     *
     * @param commentId the value for mj_comment.comment_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_comment.user_id
     *
     * @return the value of mj_comment.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_comment.user_id
     *
     * @param userId the value for mj_comment.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_comment.article_id
     *
     * @return the value of mj_comment.article_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_comment.article_id
     *
     * @param articleId the value for mj_comment.article_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_comment.content
     *
     * @return the value of mj_comment.content
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_comment.content
     *
     * @param content the value for mj_comment.content
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_comment.create_time
     *
     * @return the value of mj_comment.create_time
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_comment.create_time
     *
     * @param createTime the value for mj_comment.create_time
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_comment
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", userId=").append(userId);
        sb.append(", articleId=").append(articleId);
        sb.append(", content=").append(content);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}