package com.talaash.entity;

import java.io.Serializable;
import java.util.Date;

public class DisappearedPerson implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.dis_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer disId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.gender
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.nationality
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.age
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.province
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.city
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.county
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.identity_number
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String identityNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.person_height
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer personHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.photo
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.miss_date
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Date missDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.miss_place
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String missPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.maybe_place
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String maybePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.miss_type
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer missType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.reward
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Double reward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.findType
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer findtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.contant_name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String contantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.contant_phone
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String contantPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.contant_address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String contantAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.contant_wechat
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String contantWechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.examine_statu
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer examineStatu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.del_statu
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer delStatu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_disappeared_person.detailed_inf
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String detailedInf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.dis_id
     *
     * @return the value of mj_disappeared_person.dis_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getDisId() {
        return disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.dis_id
     *
     * @param disId the value for mj_disappeared_person.dis_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setDisId(Integer disId) {
        this.disId = disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.user_id
     *
     * @return the value of mj_disappeared_person.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.user_id
     *
     * @param userId the value for mj_disappeared_person.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.name
     *
     * @return the value of mj_disappeared_person.name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.name
     *
     * @param name the value for mj_disappeared_person.name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.gender
     *
     * @return the value of mj_disappeared_person.gender
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.gender
     *
     * @param gender the value for mj_disappeared_person.gender
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.nationality
     *
     * @return the value of mj_disappeared_person.nationality
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.nationality
     *
     * @param nationality the value for mj_disappeared_person.nationality
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.age
     *
     * @return the value of mj_disappeared_person.age
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.age
     *
     * @param age the value for mj_disappeared_person.age
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.province
     *
     * @return the value of mj_disappeared_person.province
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.province
     *
     * @param province the value for mj_disappeared_person.province
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.city
     *
     * @return the value of mj_disappeared_person.city
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.city
     *
     * @param city the value for mj_disappeared_person.city
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.county
     *
     * @return the value of mj_disappeared_person.county
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.county
     *
     * @param county the value for mj_disappeared_person.county
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setCounty(Integer county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.address
     *
     * @return the value of mj_disappeared_person.address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.address
     *
     * @param address the value for mj_disappeared_person.address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.identity_number
     *
     * @return the value of mj_disappeared_person.identity_number
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getIdentityNumber() {
        return identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.identity_number
     *
     * @param identityNumber the value for mj_disappeared_person.identity_number
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setIdentityNumber(String identityNumber) {
        this.identityNumber = identityNumber == null ? null : identityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.person_height
     *
     * @return the value of mj_disappeared_person.person_height
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getPersonHeight() {
        return personHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.person_height
     *
     * @param personHeight the value for mj_disappeared_person.person_height
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setPersonHeight(Integer personHeight) {
        this.personHeight = personHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.photo
     *
     * @return the value of mj_disappeared_person.photo
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.photo
     *
     * @param photo the value for mj_disappeared_person.photo
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.miss_date
     *
     * @return the value of mj_disappeared_person.miss_date
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Date getMissDate() {
        return missDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.miss_date
     *
     * @param missDate the value for mj_disappeared_person.miss_date
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setMissDate(Date missDate) {
        this.missDate = missDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.miss_place
     *
     * @return the value of mj_disappeared_person.miss_place
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getMissPlace() {
        return missPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.miss_place
     *
     * @param missPlace the value for mj_disappeared_person.miss_place
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setMissPlace(String missPlace) {
        this.missPlace = missPlace == null ? null : missPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.maybe_place
     *
     * @return the value of mj_disappeared_person.maybe_place
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getMaybePlace() {
        return maybePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.maybe_place
     *
     * @param maybePlace the value for mj_disappeared_person.maybe_place
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setMaybePlace(String maybePlace) {
        this.maybePlace = maybePlace == null ? null : maybePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.miss_type
     *
     * @return the value of mj_disappeared_person.miss_type
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getMissType() {
        return missType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.miss_type
     *
     * @param missType the value for mj_disappeared_person.miss_type
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setMissType(Integer missType) {
        this.missType = missType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.reward
     *
     * @return the value of mj_disappeared_person.reward
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Double getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.reward
     *
     * @param reward the value for mj_disappeared_person.reward
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setReward(Double reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.findType
     *
     * @return the value of mj_disappeared_person.findType
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getFindtype() {
        return findtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.findType
     *
     * @param findtype the value for mj_disappeared_person.findType
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFindtype(Integer findtype) {
        this.findtype = findtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.contant_name
     *
     * @return the value of mj_disappeared_person.contant_name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getContantName() {
        return contantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.contant_name
     *
     * @param contantName the value for mj_disappeared_person.contant_name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setContantName(String contantName) {
        this.contantName = contantName == null ? null : contantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.contant_phone
     *
     * @return the value of mj_disappeared_person.contant_phone
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getContantPhone() {
        return contantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.contant_phone
     *
     * @param contantPhone the value for mj_disappeared_person.contant_phone
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setContantPhone(String contantPhone) {
        this.contantPhone = contantPhone == null ? null : contantPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.contant_address
     *
     * @return the value of mj_disappeared_person.contant_address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getContantAddress() {
        return contantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.contant_address
     *
     * @param contantAddress the value for mj_disappeared_person.contant_address
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setContantAddress(String contantAddress) {
        this.contantAddress = contantAddress == null ? null : contantAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.contant_wechat
     *
     * @return the value of mj_disappeared_person.contant_wechat
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getContantWechat() {
        return contantWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.contant_wechat
     *
     * @param contantWechat the value for mj_disappeared_person.contant_wechat
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setContantWechat(String contantWechat) {
        this.contantWechat = contantWechat == null ? null : contantWechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.examine_statu
     *
     * @return the value of mj_disappeared_person.examine_statu
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getExamineStatu() {
        return examineStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.examine_statu
     *
     * @param examineStatu the value for mj_disappeared_person.examine_statu
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setExamineStatu(Integer examineStatu) {
        this.examineStatu = examineStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.del_statu
     *
     * @return the value of mj_disappeared_person.del_statu
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getDelStatu() {
        return delStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.del_statu
     *
     * @param delStatu the value for mj_disappeared_person.del_statu
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setDelStatu(Integer delStatu) {
        this.delStatu = delStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_disappeared_person.detailed_inf
     *
     * @return the value of mj_disappeared_person.detailed_inf
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getDetailedInf() {
        return detailedInf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_disappeared_person.detailed_inf
     *
     * @param detailedInf the value for mj_disappeared_person.detailed_inf
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setDetailedInf(String detailedInf) {
        this.detailedInf = detailedInf == null ? null : detailedInf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", disId=").append(disId);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", nationality=").append(nationality);
        sb.append(", age=").append(age);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", county=").append(county);
        sb.append(", address=").append(address);
        sb.append(", identityNumber=").append(identityNumber);
        sb.append(", personHeight=").append(personHeight);
        sb.append(", photo=").append(photo);
        sb.append(", missDate=").append(missDate);
        sb.append(", missPlace=").append(missPlace);
        sb.append(", maybePlace=").append(maybePlace);
        sb.append(", missType=").append(missType);
        sb.append(", reward=").append(reward);
        sb.append(", findtype=").append(findtype);
        sb.append(", contantName=").append(contantName);
        sb.append(", contantPhone=").append(contantPhone);
        sb.append(", contantAddress=").append(contantAddress);
        sb.append(", contantWechat=").append(contantWechat);
        sb.append(", examineStatu=").append(examineStatu);
        sb.append(", delStatu=").append(delStatu);
        sb.append(", detailedInf=").append(detailedInf);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}