package com.talaash.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DisappearedPersonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public DisappearedPersonExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andDisIdIsNull() {
            addCriterion("dis_id is null");
            return (Criteria) this;
        }

        public Criteria andDisIdIsNotNull() {
            addCriterion("dis_id is not null");
            return (Criteria) this;
        }

        public Criteria andDisIdEqualTo(Integer value) {
            addCriterion("dis_id =", value, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdNotEqualTo(Integer value) {
            addCriterion("dis_id <>", value, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdGreaterThan(Integer value) {
            addCriterion("dis_id >", value, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dis_id >=", value, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdLessThan(Integer value) {
            addCriterion("dis_id <", value, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdLessThanOrEqualTo(Integer value) {
            addCriterion("dis_id <=", value, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdIn(List<Integer> values) {
            addCriterion("dis_id in", values, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdNotIn(List<Integer> values) {
            addCriterion("dis_id not in", values, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdBetween(Integer value1, Integer value2) {
            addCriterion("dis_id between", value1, value2, "disId");
            return (Criteria) this;
        }

        public Criteria andDisIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dis_id not between", value1, value2, "disId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNull() {
            addCriterion("nationality is null");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNotNull() {
            addCriterion("nationality is not null");
            return (Criteria) this;
        }

        public Criteria andNationalityEqualTo(String value) {
            addCriterion("nationality =", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotEqualTo(String value) {
            addCriterion("nationality <>", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThan(String value) {
            addCriterion("nationality >", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThanOrEqualTo(String value) {
            addCriterion("nationality >=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThan(String value) {
            addCriterion("nationality <", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThanOrEqualTo(String value) {
            addCriterion("nationality <=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLike(String value) {
            addCriterion("nationality like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotLike(String value) {
            addCriterion("nationality not like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityIn(List<String> values) {
            addCriterion("nationality in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotIn(List<String> values) {
            addCriterion("nationality not in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityBetween(String value1, String value2) {
            addCriterion("nationality between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotBetween(String value1, String value2) {
            addCriterion("nationality not between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(Integer value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(Integer value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(Integer value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(Integer value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(Integer value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(Integer value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<Integer> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<Integer> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(Integer value1, Integer value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(Integer value1, Integer value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(Integer value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(Integer value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(Integer value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(Integer value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(Integer value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(Integer value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<Integer> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<Integer> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(Integer value1, Integer value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(Integer value1, Integer value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCountyIsNull() {
            addCriterion("county is null");
            return (Criteria) this;
        }

        public Criteria andCountyIsNotNull() {
            addCriterion("county is not null");
            return (Criteria) this;
        }

        public Criteria andCountyEqualTo(Integer value) {
            addCriterion("county =", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotEqualTo(Integer value) {
            addCriterion("county <>", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThan(Integer value) {
            addCriterion("county >", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThanOrEqualTo(Integer value) {
            addCriterion("county >=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThan(Integer value) {
            addCriterion("county <", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThanOrEqualTo(Integer value) {
            addCriterion("county <=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyIn(List<Integer> values) {
            addCriterion("county in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotIn(List<Integer> values) {
            addCriterion("county not in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyBetween(Integer value1, Integer value2) {
            addCriterion("county between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotBetween(Integer value1, Integer value2) {
            addCriterion("county not between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberIsNull() {
            addCriterion("identity_number is null");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberIsNotNull() {
            addCriterion("identity_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberEqualTo(String value) {
            addCriterion("identity_number =", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberNotEqualTo(String value) {
            addCriterion("identity_number <>", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberGreaterThan(String value) {
            addCriterion("identity_number >", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberGreaterThanOrEqualTo(String value) {
            addCriterion("identity_number >=", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberLessThan(String value) {
            addCriterion("identity_number <", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberLessThanOrEqualTo(String value) {
            addCriterion("identity_number <=", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberLike(String value) {
            addCriterion("identity_number like", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberNotLike(String value) {
            addCriterion("identity_number not like", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberIn(List<String> values) {
            addCriterion("identity_number in", values, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberNotIn(List<String> values) {
            addCriterion("identity_number not in", values, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberBetween(String value1, String value2) {
            addCriterion("identity_number between", value1, value2, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberNotBetween(String value1, String value2) {
            addCriterion("identity_number not between", value1, value2, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andPersonHeightIsNull() {
            addCriterion("person_height is null");
            return (Criteria) this;
        }

        public Criteria andPersonHeightIsNotNull() {
            addCriterion("person_height is not null");
            return (Criteria) this;
        }

        public Criteria andPersonHeightEqualTo(Integer value) {
            addCriterion("person_height =", value, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightNotEqualTo(Integer value) {
            addCriterion("person_height <>", value, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightGreaterThan(Integer value) {
            addCriterion("person_height >", value, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("person_height >=", value, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightLessThan(Integer value) {
            addCriterion("person_height <", value, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightLessThanOrEqualTo(Integer value) {
            addCriterion("person_height <=", value, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightIn(List<Integer> values) {
            addCriterion("person_height in", values, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightNotIn(List<Integer> values) {
            addCriterion("person_height not in", values, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightBetween(Integer value1, Integer value2) {
            addCriterion("person_height between", value1, value2, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPersonHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("person_height not between", value1, value2, "personHeight");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNull() {
            addCriterion("photo is null");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNotNull() {
            addCriterion("photo is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoEqualTo(String value) {
            addCriterion("photo =", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotEqualTo(String value) {
            addCriterion("photo <>", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThan(String value) {
            addCriterion("photo >", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("photo >=", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLessThan(String value) {
            addCriterion("photo <", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLessThanOrEqualTo(String value) {
            addCriterion("photo <=", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLike(String value) {
            addCriterion("photo like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotLike(String value) {
            addCriterion("photo not like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoIn(List<String> values) {
            addCriterion("photo in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotIn(List<String> values) {
            addCriterion("photo not in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoBetween(String value1, String value2) {
            addCriterion("photo between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotBetween(String value1, String value2) {
            addCriterion("photo not between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andMissDateIsNull() {
            addCriterion("miss_date is null");
            return (Criteria) this;
        }

        public Criteria andMissDateIsNotNull() {
            addCriterion("miss_date is not null");
            return (Criteria) this;
        }

        public Criteria andMissDateEqualTo(Date value) {
            addCriterionForJDBCDate("miss_date =", value, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("miss_date <>", value, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateGreaterThan(Date value) {
            addCriterionForJDBCDate("miss_date >", value, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("miss_date >=", value, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateLessThan(Date value) {
            addCriterionForJDBCDate("miss_date <", value, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("miss_date <=", value, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateIn(List<Date> values) {
            addCriterionForJDBCDate("miss_date in", values, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("miss_date not in", values, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("miss_date between", value1, value2, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("miss_date not between", value1, value2, "missDate");
            return (Criteria) this;
        }

        public Criteria andMissPlaceIsNull() {
            addCriterion("miss_place is null");
            return (Criteria) this;
        }

        public Criteria andMissPlaceIsNotNull() {
            addCriterion("miss_place is not null");
            return (Criteria) this;
        }

        public Criteria andMissPlaceEqualTo(String value) {
            addCriterion("miss_place =", value, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceNotEqualTo(String value) {
            addCriterion("miss_place <>", value, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceGreaterThan(String value) {
            addCriterion("miss_place >", value, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("miss_place >=", value, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceLessThan(String value) {
            addCriterion("miss_place <", value, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceLessThanOrEqualTo(String value) {
            addCriterion("miss_place <=", value, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceLike(String value) {
            addCriterion("miss_place like", value, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceNotLike(String value) {
            addCriterion("miss_place not like", value, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceIn(List<String> values) {
            addCriterion("miss_place in", values, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceNotIn(List<String> values) {
            addCriterion("miss_place not in", values, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceBetween(String value1, String value2) {
            addCriterion("miss_place between", value1, value2, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMissPlaceNotBetween(String value1, String value2) {
            addCriterion("miss_place not between", value1, value2, "missPlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceIsNull() {
            addCriterion("maybe_place is null");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceIsNotNull() {
            addCriterion("maybe_place is not null");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceEqualTo(String value) {
            addCriterion("maybe_place =", value, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceNotEqualTo(String value) {
            addCriterion("maybe_place <>", value, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceGreaterThan(String value) {
            addCriterion("maybe_place >", value, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("maybe_place >=", value, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceLessThan(String value) {
            addCriterion("maybe_place <", value, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceLessThanOrEqualTo(String value) {
            addCriterion("maybe_place <=", value, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceLike(String value) {
            addCriterion("maybe_place like", value, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceNotLike(String value) {
            addCriterion("maybe_place not like", value, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceIn(List<String> values) {
            addCriterion("maybe_place in", values, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceNotIn(List<String> values) {
            addCriterion("maybe_place not in", values, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceBetween(String value1, String value2) {
            addCriterion("maybe_place between", value1, value2, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMaybePlaceNotBetween(String value1, String value2) {
            addCriterion("maybe_place not between", value1, value2, "maybePlace");
            return (Criteria) this;
        }

        public Criteria andMissTypeIsNull() {
            addCriterion("miss_type is null");
            return (Criteria) this;
        }

        public Criteria andMissTypeIsNotNull() {
            addCriterion("miss_type is not null");
            return (Criteria) this;
        }

        public Criteria andMissTypeEqualTo(Integer value) {
            addCriterion("miss_type =", value, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeNotEqualTo(Integer value) {
            addCriterion("miss_type <>", value, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeGreaterThan(Integer value) {
            addCriterion("miss_type >", value, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("miss_type >=", value, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeLessThan(Integer value) {
            addCriterion("miss_type <", value, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeLessThanOrEqualTo(Integer value) {
            addCriterion("miss_type <=", value, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeIn(List<Integer> values) {
            addCriterion("miss_type in", values, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeNotIn(List<Integer> values) {
            addCriterion("miss_type not in", values, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeBetween(Integer value1, Integer value2) {
            addCriterion("miss_type between", value1, value2, "missType");
            return (Criteria) this;
        }

        public Criteria andMissTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("miss_type not between", value1, value2, "missType");
            return (Criteria) this;
        }

        public Criteria andRewardIsNull() {
            addCriterion("reward is null");
            return (Criteria) this;
        }

        public Criteria andRewardIsNotNull() {
            addCriterion("reward is not null");
            return (Criteria) this;
        }

        public Criteria andRewardEqualTo(Double value) {
            addCriterion("reward =", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotEqualTo(Double value) {
            addCriterion("reward <>", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThan(Double value) {
            addCriterion("reward >", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThanOrEqualTo(Double value) {
            addCriterion("reward >=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThan(Double value) {
            addCriterion("reward <", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThanOrEqualTo(Double value) {
            addCriterion("reward <=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardIn(List<Double> values) {
            addCriterion("reward in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotIn(List<Double> values) {
            addCriterion("reward not in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardBetween(Double value1, Double value2) {
            addCriterion("reward between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotBetween(Double value1, Double value2) {
            addCriterion("reward not between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andFindtypeIsNull() {
            addCriterion("findType is null");
            return (Criteria) this;
        }

        public Criteria andFindtypeIsNotNull() {
            addCriterion("findType is not null");
            return (Criteria) this;
        }

        public Criteria andFindtypeEqualTo(Integer value) {
            addCriterion("findType =", value, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeNotEqualTo(Integer value) {
            addCriterion("findType <>", value, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeGreaterThan(Integer value) {
            addCriterion("findType >", value, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("findType >=", value, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeLessThan(Integer value) {
            addCriterion("findType <", value, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeLessThanOrEqualTo(Integer value) {
            addCriterion("findType <=", value, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeIn(List<Integer> values) {
            addCriterion("findType in", values, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeNotIn(List<Integer> values) {
            addCriterion("findType not in", values, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeBetween(Integer value1, Integer value2) {
            addCriterion("findType between", value1, value2, "findtype");
            return (Criteria) this;
        }

        public Criteria andFindtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("findType not between", value1, value2, "findtype");
            return (Criteria) this;
        }

        public Criteria andContantNameIsNull() {
            addCriterion("contant_name is null");
            return (Criteria) this;
        }

        public Criteria andContantNameIsNotNull() {
            addCriterion("contant_name is not null");
            return (Criteria) this;
        }

        public Criteria andContantNameEqualTo(String value) {
            addCriterion("contant_name =", value, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameNotEqualTo(String value) {
            addCriterion("contant_name <>", value, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameGreaterThan(String value) {
            addCriterion("contant_name >", value, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameGreaterThanOrEqualTo(String value) {
            addCriterion("contant_name >=", value, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameLessThan(String value) {
            addCriterion("contant_name <", value, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameLessThanOrEqualTo(String value) {
            addCriterion("contant_name <=", value, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameLike(String value) {
            addCriterion("contant_name like", value, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameNotLike(String value) {
            addCriterion("contant_name not like", value, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameIn(List<String> values) {
            addCriterion("contant_name in", values, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameNotIn(List<String> values) {
            addCriterion("contant_name not in", values, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameBetween(String value1, String value2) {
            addCriterion("contant_name between", value1, value2, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantNameNotBetween(String value1, String value2) {
            addCriterion("contant_name not between", value1, value2, "contantName");
            return (Criteria) this;
        }

        public Criteria andContantPhoneIsNull() {
            addCriterion("contant_phone is null");
            return (Criteria) this;
        }

        public Criteria andContantPhoneIsNotNull() {
            addCriterion("contant_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContantPhoneEqualTo(String value) {
            addCriterion("contant_phone =", value, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneNotEqualTo(String value) {
            addCriterion("contant_phone <>", value, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneGreaterThan(String value) {
            addCriterion("contant_phone >", value, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("contant_phone >=", value, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneLessThan(String value) {
            addCriterion("contant_phone <", value, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneLessThanOrEqualTo(String value) {
            addCriterion("contant_phone <=", value, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneLike(String value) {
            addCriterion("contant_phone like", value, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneNotLike(String value) {
            addCriterion("contant_phone not like", value, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneIn(List<String> values) {
            addCriterion("contant_phone in", values, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneNotIn(List<String> values) {
            addCriterion("contant_phone not in", values, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneBetween(String value1, String value2) {
            addCriterion("contant_phone between", value1, value2, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantPhoneNotBetween(String value1, String value2) {
            addCriterion("contant_phone not between", value1, value2, "contantPhone");
            return (Criteria) this;
        }

        public Criteria andContantAddressIsNull() {
            addCriterion("contant_address is null");
            return (Criteria) this;
        }

        public Criteria andContantAddressIsNotNull() {
            addCriterion("contant_address is not null");
            return (Criteria) this;
        }

        public Criteria andContantAddressEqualTo(String value) {
            addCriterion("contant_address =", value, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressNotEqualTo(String value) {
            addCriterion("contant_address <>", value, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressGreaterThan(String value) {
            addCriterion("contant_address >", value, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressGreaterThanOrEqualTo(String value) {
            addCriterion("contant_address >=", value, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressLessThan(String value) {
            addCriterion("contant_address <", value, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressLessThanOrEqualTo(String value) {
            addCriterion("contant_address <=", value, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressLike(String value) {
            addCriterion("contant_address like", value, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressNotLike(String value) {
            addCriterion("contant_address not like", value, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressIn(List<String> values) {
            addCriterion("contant_address in", values, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressNotIn(List<String> values) {
            addCriterion("contant_address not in", values, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressBetween(String value1, String value2) {
            addCriterion("contant_address between", value1, value2, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantAddressNotBetween(String value1, String value2) {
            addCriterion("contant_address not between", value1, value2, "contantAddress");
            return (Criteria) this;
        }

        public Criteria andContantWechatIsNull() {
            addCriterion("contant_wechat is null");
            return (Criteria) this;
        }

        public Criteria andContantWechatIsNotNull() {
            addCriterion("contant_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andContantWechatEqualTo(String value) {
            addCriterion("contant_wechat =", value, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatNotEqualTo(String value) {
            addCriterion("contant_wechat <>", value, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatGreaterThan(String value) {
            addCriterion("contant_wechat >", value, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatGreaterThanOrEqualTo(String value) {
            addCriterion("contant_wechat >=", value, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatLessThan(String value) {
            addCriterion("contant_wechat <", value, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatLessThanOrEqualTo(String value) {
            addCriterion("contant_wechat <=", value, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatLike(String value) {
            addCriterion("contant_wechat like", value, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatNotLike(String value) {
            addCriterion("contant_wechat not like", value, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatIn(List<String> values) {
            addCriterion("contant_wechat in", values, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatNotIn(List<String> values) {
            addCriterion("contant_wechat not in", values, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatBetween(String value1, String value2) {
            addCriterion("contant_wechat between", value1, value2, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andContantWechatNotBetween(String value1, String value2) {
            addCriterion("contant_wechat not between", value1, value2, "contantWechat");
            return (Criteria) this;
        }

        public Criteria andExamineStatuIsNull() {
            addCriterion("examine_statu is null");
            return (Criteria) this;
        }

        public Criteria andExamineStatuIsNotNull() {
            addCriterion("examine_statu is not null");
            return (Criteria) this;
        }

        public Criteria andExamineStatuEqualTo(Integer value) {
            addCriterion("examine_statu =", value, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuNotEqualTo(Integer value) {
            addCriterion("examine_statu <>", value, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuGreaterThan(Integer value) {
            addCriterion("examine_statu >", value, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuGreaterThanOrEqualTo(Integer value) {
            addCriterion("examine_statu >=", value, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuLessThan(Integer value) {
            addCriterion("examine_statu <", value, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuLessThanOrEqualTo(Integer value) {
            addCriterion("examine_statu <=", value, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuIn(List<Integer> values) {
            addCriterion("examine_statu in", values, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuNotIn(List<Integer> values) {
            addCriterion("examine_statu not in", values, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuBetween(Integer value1, Integer value2) {
            addCriterion("examine_statu between", value1, value2, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andExamineStatuNotBetween(Integer value1, Integer value2) {
            addCriterion("examine_statu not between", value1, value2, "examineStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuIsNull() {
            addCriterion("del_statu is null");
            return (Criteria) this;
        }

        public Criteria andDelStatuIsNotNull() {
            addCriterion("del_statu is not null");
            return (Criteria) this;
        }

        public Criteria andDelStatuEqualTo(Integer value) {
            addCriterion("del_statu =", value, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuNotEqualTo(Integer value) {
            addCriterion("del_statu <>", value, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuGreaterThan(Integer value) {
            addCriterion("del_statu >", value, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuGreaterThanOrEqualTo(Integer value) {
            addCriterion("del_statu >=", value, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuLessThan(Integer value) {
            addCriterion("del_statu <", value, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuLessThanOrEqualTo(Integer value) {
            addCriterion("del_statu <=", value, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuIn(List<Integer> values) {
            addCriterion("del_statu in", values, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuNotIn(List<Integer> values) {
            addCriterion("del_statu not in", values, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuBetween(Integer value1, Integer value2) {
            addCriterion("del_statu between", value1, value2, "delStatu");
            return (Criteria) this;
        }

        public Criteria andDelStatuNotBetween(Integer value1, Integer value2) {
            addCriterion("del_statu not between", value1, value2, "delStatu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 26 16:58:15 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mj_disappeared_person
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}