package com.talaash.entity;

import java.io.Serializable;
import java.util.Date;

public class Family implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_family.family_id
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    private Integer familyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_family.user_id
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_family.family_name
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    private String familyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_family.family_gender
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    private Integer familyGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_family.family_birthday
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    private Date familyBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_family.relationship
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    private String relationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_family.family_id
     *
     * @return the value of mj_family.family_id
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public Integer getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_family.family_id
     *
     * @param familyId the value for mj_family.family_id
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public void setFamilyId(Integer familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_family.user_id
     *
     * @return the value of mj_family.user_id
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_family.user_id
     *
     * @param userId the value for mj_family.user_id
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_family.family_name
     *
     * @return the value of mj_family.family_name
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_family.family_name
     *
     * @param familyName the value for mj_family.family_name
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_family.family_gender
     *
     * @return the value of mj_family.family_gender
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public Integer getFamilyGender() {
        return familyGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_family.family_gender
     *
     * @param familyGender the value for mj_family.family_gender
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public void setFamilyGender(Integer familyGender) {
        this.familyGender = familyGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_family.family_birthday
     *
     * @return the value of mj_family.family_birthday
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public Date getFamilyBirthday() {
        return familyBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_family.family_birthday
     *
     * @param familyBirthday the value for mj_family.family_birthday
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public void setFamilyBirthday(Date familyBirthday) {
        this.familyBirthday = familyBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_family.relationship
     *
     * @return the value of mj_family.relationship
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_family.relationship
     *
     * @param relationship the value for mj_family.relationship
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship == null ? null : relationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_family
     *
     * @mbg.generated Thu Mar 26 20:48:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", familyId=").append(familyId);
        sb.append(", userId=").append(userId);
        sb.append(", familyName=").append(familyName);
        sb.append(", familyGender=").append(familyGender);
        sb.append(", familyBirthday=").append(familyBirthday);
        sb.append(", relationship=").append(relationship);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}