package com.talaash.entity;

import java.io.Serializable;

public class Finger implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_finger.finger_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer fingerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_finger.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_finger.family_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer familyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_finger.finger_name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String fingerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_finger.finger_pic
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String fingerPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_finger.finger_code
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String fingerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_finger
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_finger.finger_id
     *
     * @return the value of mj_finger.finger_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getFingerId() {
        return fingerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_finger.finger_id
     *
     * @param fingerId the value for mj_finger.finger_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFingerId(Integer fingerId) {
        this.fingerId = fingerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_finger.user_id
     *
     * @return the value of mj_finger.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_finger.user_id
     *
     * @param userId the value for mj_finger.user_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_finger.family_id
     *
     * @return the value of mj_finger.family_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_finger.family_id
     *
     * @param familyId the value for mj_finger.family_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFamilyId(Integer familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_finger.finger_name
     *
     * @return the value of mj_finger.finger_name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getFingerName() {
        return fingerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_finger.finger_name
     *
     * @param fingerName the value for mj_finger.finger_name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFingerName(String fingerName) {
        this.fingerName = fingerName == null ? null : fingerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_finger.finger_pic
     *
     * @return the value of mj_finger.finger_pic
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getFingerPic() {
        return fingerPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_finger.finger_pic
     *
     * @param fingerPic the value for mj_finger.finger_pic
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFingerPic(String fingerPic) {
        this.fingerPic = fingerPic == null ? null : fingerPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_finger.finger_code
     *
     * @return the value of mj_finger.finger_code
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getFingerCode() {
        return fingerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_finger.finger_code
     *
     * @param fingerCode the value for mj_finger.finger_code
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFingerCode(String fingerCode) {
        this.fingerCode = fingerCode == null ? null : fingerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_finger
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fingerId=").append(fingerId);
        sb.append(", userId=").append(userId);
        sb.append(", familyId=").append(familyId);
        sb.append(", fingerName=").append(fingerName);
        sb.append(", fingerPic=").append(fingerPic);
        sb.append(", fingerCode=").append(fingerCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}