package com.talaash.entity;

import java.io.Serializable;

public class FriendLinkage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_friend_linkage.fid
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_friend_linkage.fname
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_friend_linkage.url
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_friend_linkage.picture
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_friend_linkage.fid
     *
     * @return the value of mj_friend_linkage.fid
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_friend_linkage.fid
     *
     * @param fid the value for mj_friend_linkage.fid
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_friend_linkage.fname
     *
     * @return the value of mj_friend_linkage.fname
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_friend_linkage.fname
     *
     * @param fname the value for mj_friend_linkage.fname
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_friend_linkage.url
     *
     * @return the value of mj_friend_linkage.url
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_friend_linkage.url
     *
     * @param url the value for mj_friend_linkage.url
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_friend_linkage.picture
     *
     * @return the value of mj_friend_linkage.picture
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_friend_linkage.picture
     *
     * @param picture the value for mj_friend_linkage.picture
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_friend_linkage
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fid=").append(fid);
        sb.append(", fname=").append(fname);
        sb.append(", url=").append(url);
        sb.append(", picture=").append(picture);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}