package com.talaash.entity;

import java.io.Serializable;

public class Region implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_region.id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_region.code
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_region.name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_region.parent_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_region.first_letter
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private String firstLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mj_region.level
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mj_region
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_region.id
     *
     * @return the value of mj_region.id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_region.id
     *
     * @param id the value for mj_region.id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_region.code
     *
     * @return the value of mj_region.code
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_region.code
     *
     * @param code the value for mj_region.code
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_region.name
     *
     * @return the value of mj_region.name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_region.name
     *
     * @param name the value for mj_region.name
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_region.parent_id
     *
     * @return the value of mj_region.parent_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_region.parent_id
     *
     * @param parentId the value for mj_region.parent_id
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_region.first_letter
     *
     * @return the value of mj_region.first_letter
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_region.first_letter
     *
     * @param firstLetter the value for mj_region.first_letter
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter == null ? null : firstLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mj_region.level
     *
     * @return the value of mj_region.level
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mj_region.level
     *
     * @param level the value for mj_region.level
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mj_region
     *
     * @mbg.generated Thu Mar 26 16:58:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", parentId=").append(parentId);
        sb.append(", firstLetter=").append(firstLetter);
        sb.append(", level=").append(level);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}